### ISSUE TITLE
Highlight color for current date can't be changed

### ISSUE THREAD

**Issue by jordibruin** [vishalvshekkar/SwiftCalendar#11]
The color that is used for the current date when it is highlighted can't be set. This makes the text not very readable if the color of the selected date is too close to the text color. Any help would be appreciated!

**Comment by vishalvshekkar** [comment]
Hey, the current date highlight color, I believe has been hardcoded somewhere. You can feel free to add a property and expose it so you can change it and raise a pull request. I'm a bit busy right now, and am looking to revamp the whole thing when I get time. Until then, the changes you would make would help yourself and others. Thanks.
