### ISSUE TITLE
No way to highlight selected date except by reloading entire calendar

### ISSUE THREAD

**Issue by lnjustin** [vishalvshekkar/SwiftCalendar#5]
Unless I am missing something, I don't see a straightforward way to highlight whichever date is selected, at least not without reloading the entire calendar. Modifications in this regard would be important for a number of calendar uses. Thanks.

**Comment by vishalvshekkar** [comment]
You're right. I'm working on something else right now. I'll get on to it as soon as I can. Thank you.

**Comment by vishalvshekkar** [comment]
Please submit a pull request if you have a fix for this. I'm not able to find time to sit and fix this.

**Comment by lnjustin** [comment]
Ok. I do have a fairly simple fix. I'll submit it.

**Comment by vishalvshekkar** [comment]
Thank you.

**Comment by vishalvshekkar** [comment]
I have modified the whole code and it has been improved to a good extent.
