### ISSUE TITLE
Performance Trouble With Lots of Events

### ISSUE THREAD

**Issue by lnjustin** [vishalvshekkar/SwiftCalendar#6]
The calendar loads into memory all of your events (for all of time) at setup. I find that performance in terms of initial load time suffers as a result when there are lots of events. I would like to see there be a way to dynamically add eventHighlightStruct objects to the events array (and add continuousEventStruct objects to the continuousEvents array) as the user scrolls through the calendar. Sort of like the calendar dynamically adds more base views to the monthsInMemory array.

**Comment by vishalvshekkar** [comment]
You're right about that. When I first created the calendar with the events, I only had  3 months' worth of events in mind. The performance is crappy, I agree.
Please submit a pull request if you have a fix for this. I'm not able to find time to fix this.

**Comment by vishalvshekkar** [comment]
Performance has now been improved greatly. Please check.

**Comment by lnjustin** [comment]
I will take a closer look and test the performance. But at first glance I’m intrigued. Can you briefly describe what the different event types are supposed to be (unconfirmed, unavailable, etc.)? I just notice a few things. I am noticing that it doesn’t seem like I can have multiple events on the same day anymore. Is that right? Also, the vertical view has a lot of space between months.
Justin
