### ISSUE TITLE
presentMonth quick fix

### ISSUE THREAD

**Issue by lnjustin** [vishalvshekkar/SwiftCalendar#7]
presentMonth needs to be incremented by 1 in the function previousMonth if presentIndex.item < 2. Otherwise presentMonth incorrectly stays at 1 when you scroll to a previous month, when it should be made 2 at this point. Like this:

```
fun previousMonth(presentIndex: NSIndexPath) {
    if presentIndex.item < 2 {
          ....
         presentMonth += 1
    }
}
```

**Comment by vishalvshekkar** [comment]
Please submit a pull request with the changes, if you can.

**Comment by vishalvshekkar** [comment]
Present month can now be obtained from collection view Index Path for Item. I haven't given a straight forward way to obtain the present month, but, it can be done. I will add this soon.
