### ISSUE TITLE
Great update. Just needs pagination and customizable month name placement

### ISSUE THREAD

**Issue by lnjustin** [vishalvshekkar/SwiftCalendar#8]
The old calendar's pagination feature was much preferred to the continuous scroll. Please update as an option. Also, I find the month name and year to be much too small. Again, I prefer the old calendar's more prominent and static display of that in a top label above the calendar.

**Comment by vishalvshekkar** [comment]
Yes. The pagination is something I'll add to this soon. It requires a simple customisation of CollectionViewFlowLayout. Changing the calendar months from another class is not possible in the new one. I'll fix them soon.

The weekday labels above each month is something I'll add to this.

The last update was mainly focussed on performance. Also, the day buttons are interactive now. You can toggle events by tapping on the days.

**Comment by lnjustin** [comment]
Great! Yes, I propose that you give the developer the option of either using the "in-line" month and year label as you currently have in the new "twin calendar", or revert back to using the "external" month and year label as you had in the original calendar (based on func calendar(calendar: CustomizableCalendar, monthChange: monthYearStructure) being called upon month change).

**Comment by lnjustin** [comment]
Once you're able to do this, I'll fork a version with some features I have added. The features require a good bit of customization, so I'd rather add them once to the next version rather than having to do it twice.

**Comment by lnjustin** [comment]
Hi, by chance do you think you'll have time to get to this some time fairly soon? Just trying to plan my project. Thanks!

**Comment by vishalvshekkar** [comment]
Hey... For what I've been working on in my local Repo, the weekday labels appear fixed in vertical scrolls and comes with every month for horizontal scrolls. I'll update this in this Repo by the coming Monday. Will that suit you? Would you require any other features?

**Comment by lnjustin** [comment]
Sounds like it will suit. Just need it to stay at the top of the calendar fixed, rather than being integrated into the scrolling calendar. Only other thing I need is pagination, like the original calendar. Thanks!

**Comment by lnjustin** [comment]
Just checking in on progress with this. It sounded like you were really close to completing this? Not meaning to rush you! Thanks for your work on this!

**Comment by vishalvshekkar** [comment]
Hey, I fell sick and couldn't work on it. Give me a couple of days. I'll update the repo with my latest code. I haven't done it sooner because the sample implementation needs to be changed to support the latest changes made in the calendar code. I need to work on that. I'm extremely sorry about the delay.

**Comment by lnjustin** [comment]
No problem at all. Totally understand. Thanks!

**Comment by vishalvshekkar** [comment]
Hey, I've updated the master branch. Check it out. The example code is very bare and doesn't show off all features. Please let me know if you don't find your way through it.

**Comment by lnjustin** [comment]
Perfect. Exactly what I needed. Thanks again!

**Comment by vishalvshekkar** [comment]
Awesome :)
